POST http://localhost:3001/api/login 
Content-Type: application/json

{
    "userID": "1001",
    "password": "admin123"
}


###
GET http://localhost:3001/api

###

GET http://localhost:3001/api/courses
{
    "studentID": 1001
}